/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: mes
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.panda.android.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property materialCode 物料编码
 * @property materielSerialCode 物料条码
 * @property materialName 物料名称
 * @property materialNo 型号代号
 */
@JsonClass(generateAdapter = true)
data class BindList(
    @Json(name = "materialCode") @field:Json(name = "materialCode") var materialCode: String,
    @Json(name = "materielSerialCode") @field:Json(name = "materielSerialCode") var materielSerialCode: String,
    @Json(name = "materialName") @field:Json(name = "materialName") var materialName: Int,
    @Json(name = "materialNo") @field:Json(name = "materialNo") var materialNo: String
)
