/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: mes
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.panda.android.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 * @property id 
 * @property orderNo 订单编号
 * @property planCode 计划编号
 * @property workNo 工作令号
 * @property batchNo 批次号
 * @property taskCode 任务编号
 * @property taskDesc 任务描述
 * @property productCode 产品编码
 * @property productName 产品描述
 * @property taskNum 任务数量
 * @property reportNumber 报工数量
 * @property reportTime 工时
 * @property remark 备注
 */
@JsonClass(generateAdapter = true)
data class Data7(
    @Json(name = "id") @field:Json(name = "id") var id: Int,
    @Json(name = "orderNo") @field:Json(name = "orderNo") var orderNo: String,
    @Json(name = "planCode") @field:Json(name = "planCode") var planCode: String,
    @Json(name = "workNo") @field:Json(name = "workNo") var workNo: String,
    @Json(name = "batchNo") @field:Json(name = "batchNo") var batchNo: String,
    @Json(name = "taskCode") @field:Json(name = "taskCode") var taskCode: String,
    @Json(name = "taskDesc") @field:Json(name = "taskDesc") var taskDesc: String,
    @Json(name = "productCode") @field:Json(name = "productCode") var productCode: String,
    @Json(name = "productName") @field:Json(name = "productName") var productName: String,
    @Json(name = "taskNum") @field:Json(name = "taskNum") var taskNum: Int,
    @Json(name = "reportNumber") @field:Json(name = "reportNumber") var reportNumber: Int,
    @Json(name = "reportTime") @field:Json(name = "reportTime") var reportTime: Int,
    @Json(name = "remark") @field:Json(name = "remark") var remark: String
)
