/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: mes
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.panda.android.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property productCode 产品编码
 * @property productName 产品描述
 * @property technicsCode 工艺编码
 * @property technicsDesc 工艺描述
 * @property technicsVersion 工艺版本
 * @property procedureCode 工序编码
 * @property procedureDesc 工序描述
 * @property procedureId 工序id
 * @property fileId 文件id
 * @property fileName 文件名
 * @property fileUrl 文件的key
 */
@JsonClass(generateAdapter = true)
data class DataList3(
    @Json(name = "productCode") @field:Json(name = "productCode") var productCode: String,
    @Json(name = "productName") @field:Json(name = "productName") var productName: String,
    @Json(name = "technicsCode") @field:Json(name = "technicsCode") var technicsCode: String,
    @Json(name = "technicsDesc") @field:Json(name = "technicsDesc") var technicsDesc: String,
    @Json(name = "technicsVersion") @field:Json(name = "technicsVersion") var technicsVersion: String,
    @Json(name = "procedureCode") @field:Json(name = "procedureCode") var procedureCode: String,
    @Json(name = "procedureDesc") @field:Json(name = "procedureDesc") var procedureDesc: String,
    @Json(name = "procedureId") @field:Json(name = "procedureId") var procedureId: Int,
    @Json(name = "fileId") @field:Json(name = "fileId") var fileId: Int,
    @Json(name = "fileName") @field:Json(name = "fileName") var fileName: String,
    @Json(name = "fileUrl") @field:Json(name = "fileUrl") var fileUrl: String
)
