/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: mes
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.panda.android.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 * @property totalBindCount 总已绑定个数
 * @property totalToBindCount 总需绑定物料个数
 * @property bindList 已绑定列表
 * @property toBindList 待绑定列表
 */
@JsonClass(generateAdapter = true)
data class Data10(
    @Json(name = "totalBindCount") @field:Json(name = "totalBindCount") var totalBindCount: Int,
    @Json(name = "totalToBindCount") @field:Json(name = "totalToBindCount") var totalToBindCount: Int,
    @Json(name = "bindList") @field:Json(name = "bindList") var bindList: List<BindList>,
    @Json(name = "toBindList") @field:Json(name = "toBindList") var toBindList: List<ToBindList>
)
