/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: mes
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.panda.android.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 * @property total 总个数
 * @property dataList 
 */
@JsonClass(generateAdapter = true)
data class Data12(
    @Json(name = "total") @field:Json(name = "total") var total: Int,
    @Json(name = "dataList") @field:Json(name = "dataList") var dataList: List<DataList5>
)
