/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: mes
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.panda.android.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 * @property fileUrl 文件url
 * @property fileName 文件名
 * @property fileSize 文件大小
 */
@JsonClass(generateAdapter = true)
data class Data(
    @Json(name = "fileUrl") @field:Json(name = "fileUrl") var fileUrl: String,
    @Json(name = "fileName") @field:Json(name = "fileName") var fileName: String,
    @Json(name = "fileSize") @field:Json(name = "fileSize") var fileSize: Long
)
