/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: mes
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.panda.android.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property id 主键id
 * @property alarmCode 警报编码
 * @property alarmDetail 警报详情
 * @property status 状态 1未关闭 2关闭
 * @property closeId 关闭ID
 * @property closeName 关闭姓名
 * @property closeRemark 关闭说明
 * @property createName 创建人
 * @property createTime 创建时间
 */
@JsonClass(generateAdapter = true)
data class DataList5(
    @Json(name = "id") @field:Json(name = "id") var id: Int,
    @Json(name = "alarmCode") @field:Json(name = "alarmCode") var alarmCode: String,
    @Json(name = "alarmDetail") @field:Json(name = "alarmDetail") var alarmDetail: String,
    @Json(name = "status") @field:Json(name = "status") var status: Int,
    @Json(name = "closeId") @field:Json(name = "closeId") var closeId: Int,
    @Json(name = "closeName") @field:Json(name = "closeName") var closeName: String,
    @Json(name = "closeRemark") @field:Json(name = "closeRemark") var closeRemark: String,
    @Json(name = "createName") @field:Json(name = "createName") var createName: String,
    @Json(name = "createTime") @field:Json(name = "createTime") var createTime: String
)
