/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: mes
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.panda.android.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import org.threeten.bp.ZonedDateTime

/**
 * @property id 报工记录id
 * @property taskCode 任务编号
 * @property taskDesc 任务描述
 * @property productCode 产品编号
 * @property productName 产品描述
 * @property reportNumber 报工数量
 * @property createName 报工人
 * @property createTime 报工时间
 */
@JsonClass(generateAdapter = true)
data class DataList1(
    @Json(name = "id") @field:Json(name = "id") var id: Int,
    @Json(name = "taskCode") @field:Json(name = "taskCode") var taskCode: String,
    @Json(name = "taskDesc") @field:Json(name = "taskDesc") var taskDesc: String,
    @Json(name = "productCode") @field:Json(name = "productCode") var productCode: String,
    @Json(name = "productName") @field:Json(name = "productName") var productName: String,
    @Json(name = "reportNumber") @field:Json(name = "reportNumber") var reportNumber: Int,
    @Json(name = "createName") @field:Json(name = "createName") var createName: String,
    @Json(name = "createTime") @field:Json(name = "createTime") var createTime: ZonedDateTime
)
