/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: mes
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.panda.android.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property id 
 * @property createId 创建者ID
 * @property createTime 创建时间
 * @property createName 创建者姓名
 * @property paramName 参数名称
 * @property paramValue 参数VALUE
 * @property paramDesc 参数描述
 * @property parentId 父ID
 */
@JsonClass(generateAdapter = true)
data class DataList(
    @Json(name = "id") @field:Json(name = "id") var id: Int,
    @Json(name = "createId") @field:Json(name = "createId") var createId: String,
    @Json(name = "createTime") @field:Json(name = "createTime") var createTime: String,
    @Json(name = "createName") @field:Json(name = "createName") var createName: String,
    @Json(name = "paramName") @field:Json(name = "paramName") var paramName: String,
    @Json(name = "paramValue") @field:Json(name = "paramValue") var paramValue: String,
    @Json(name = "paramDesc") @field:Json(name = "paramDesc") var paramDesc: String,
    @Json(name = "parentId") @field:Json(name = "parentId") var parentId: Int
)
