/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: mes
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.panda.android.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import org.threeten.bp.ZonedDateTime

/**
 * @property id 
 * @property taskCode 任务编号
 * @property taskDesc 任务描述
 * @property taskStatus 任务状态
 * @property taskNum 任务数量
 * @property productCode 产品编码
 * @property productName 产品描述
 * @property planCode 计划编号
 * @property workNo 工作令
 * @property batchNo 批次号
 * @property planStartTime 计划开始时间
 * @property planEndTime 计划结束时间
 * @property issueName 派工人名称
 * @property realStartTime 执行时间
 * @property reportNum 已报工数量
 * @property totalReportTime 总工时
 */
@JsonClass(generateAdapter = true)
data class DataList8(
    @Json(name = "id") @field:Json(name = "id") var id: Int,
    @Json(name = "taskCode") @field:Json(name = "taskCode") var taskCode: String,
    @Json(name = "taskDesc") @field:Json(name = "taskDesc") var taskDesc: String,
    @Json(name = "taskStatus") @field:Json(name = "taskStatus") var taskStatus: Int,
    @Json(name = "taskNum") @field:Json(name = "taskNum") var taskNum: Int,
    @Json(name = "productCode") @field:Json(name = "productCode") var productCode: String,
    @Json(name = "productName") @field:Json(name = "productName") var productName: String,
    @Json(name = "planCode") @field:Json(name = "planCode") var planCode: String,
    @Json(name = "workNo") @field:Json(name = "workNo") var workNo: String,
    @Json(name = "batchNo") @field:Json(name = "batchNo") var batchNo: String,
    @Json(name = "planStartTime") @field:Json(name = "planStartTime") var planStartTime: ZonedDateTime,
    @Json(name = "planEndTime") @field:Json(name = "planEndTime") var planEndTime: ZonedDateTime,
    @Json(name = "issueName") @field:Json(name = "issueName") var issueName: String,
    @Json(name = "realStartTime") @field:Json(name = "realStartTime") var realStartTime: ZonedDateTime,
    @Json(name = "reportNum") @field:Json(name = "reportNum") var reportNum: Int,
    @Json(name = "totalReportTime") @field:Json(name = "totalReportTime") var totalReportTime: Int
)
