/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: mes
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.panda.android.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 * @property taskToReceive 任务接收
 * @property taskToRun 任务执行
 * @property taskToReport 任务报工
 * @property taskToFinish 任务完工
 */
@JsonClass(generateAdapter = true)
data class Data3(
    @Json(name = "taskToReceive") @field:Json(name = "taskToReceive") var taskToReceive: Int,
    @Json(name = "taskToRun") @field:Json(name = "taskToRun") var taskToRun: Int,
    @Json(name = "taskToReport") @field:Json(name = "taskToReport") var taskToReport: Int,
    @Json(name = "taskToFinish") @field:Json(name = "taskToFinish") var taskToFinish: Int
)
