/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: mes
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.panda.android.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property id 质检子任务id
 */
@JsonClass(generateAdapter = true)
data class EmptyObject(
    @Json(name = "id") @field:Json(name = "id") var id: Int
)
