/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: mes
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.panda.android.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.math.BigDecimal

/**
 * 
 * @property token 
 * @property userInfo
 * @property menus 菜单ID数组
 */
@JsonClass(generateAdapter = true)
data class LoginData(
    @Json(name = "token") @field:Json(name = "token") var token: String,
    @Json(name = "userInfo") @field:Json(name = "userInfo") var userInfo: UserInfo,
    @Json(name = "menus") @field:Json(name = "menus") var menus: List<BigDecimal>
)
