/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: mes
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.panda.android.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property materialCode 物料编码
 * @property materialNum 物料个数
 * @property materialName 物料描述
 * @property materialNo 型号代号
 */
@JsonClass(generateAdapter = true)
data class ToBindList(
    @Json(name = "materialCode") @field:Json(name = "materialCode") var materialCode: String,
    @Json(name = "materialNum") @field:Json(name = "materialNum") var materialNum: String,
    @Json(name = "materialName") @field:Json(name = "materialName") var materialName: String,
    @Json(name = "materialNo") @field:Json(name = "materialNo") var materialNo: String
)
